### ISSUE TITLE
tensorflow version incompatability with numpy

### ISSUE THREAD

**Issue by emlynjdavies** [SINTEF/pyopia#17]
**Describe the bug**
import pyopia.process
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\emlynd\Documents\GitHub\pyopia\pyopia\process.py", line 4, in <module>
    from skimage import morphology
  File "C:\Users\emlynd\.conda\envs\pyopia\lib\site-packages\skimage\__init__.py", line 151, in <module>
    from ._shared import geometry
  File "skimage\_shared\geometry.pyx", line 1, in init skimage._shared.geometry
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**To Reproduce**
install the environment as per README

conda install tensorflow==2.3.1

python
>> import pyopia.process

**Expected behavior**
no error on import

**Comment by emlynjdavies** [comment]
https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp

**Comment by emlynjdavies** [comment]
could potentially be fixed by using a newer version of tensorflow
